#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          bitcoin
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: bitcoind init script
# Description:       Brings the bitcoin daemon up and down at boot
### END INIT INFO
#
# written by Wesley Hinds <wesley.hinds@swri.org>

# Set to where you want your .bitcoin/ data to be stored
HOME=/
# Add path to bitcoind/bitcoin-cli executables. IE /usr/local/bin
PATH=/usr/local/bin:/bin
# Config file
BTC_CONFIG_FILE=/etc/bitcoin.conf


case "$1" in
'start')
      bitcoind -daemon -conf=$BTC_CONFIG_FILE
   ;;

'stop')
      bitcoin-cli -conf=$BTC_CONFIG_FILE stop
   ;;

'restart') echo "Restarting bitcoind....."
   [ -f /bin/kill ] && /bin/kill -HUP `pidof bitcoind`
   ;;
*)

   echo "Usage: $0 { start | stop | restart}"
   exit 1

esac
exit 0
